name: face_client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  logger: ^2.5.0
  video_player: ^2.9.5
  camera_macos: ^0.0.9
  dio: ^5.7.0
  flutter_localizations:
    sdk: flutter
  desktop_window: ^0.4.2
  socket_io_client: ^3.0.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_image_compress: ^2.4.0
  image: ^4.5.4
  flutter_webrtc: ^0.14.1
  permission_handler: ^12.0.0+1
  fast_jpeg_encoder:
    path: ./fast_jpeg_encoder
  window_size: ^0.1.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
